const books = [
  {
    title: 'Divina Comedia',
    author: 'Dante Alighieri',
    year: 1265,
    country: 'Italia',
    language: 'Italiano',
  },
  {
    title: 'Decamerón',
    author: 'Giovanni Boccaccio',
    year: 1349,
    country: 'Rávena',
    language: 'Italiano',
  },
  {
    title: 'Gargantúa y Pantagruel',
    author: 'François Rabelais',
    year: 1532,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'Cuentos infantiles',
    author: 'Hans Christian Andersen',
    year: 1835,
    country: 'Dinamarca',
    language: 'Danés',
  },
  { title: 'Guerra y paz', author: 'Lev Tolstói', year: 1865, country: 'Rusia', language: 'Ruso' },
  {
    title: 'En busca del tiempo perdido',
    author: 'Marcel Proust',
    year: 1913,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'El hombre sin atributos',
    author: 'Robert Musil',
    year: 1930,
    country: 'Austria',
    language: 'Alemán',
  },
  {
    title: 'Gente independiente',
    author: 'Halldór Laxness',
    year: 1934,
    country: 'Islandia',
    language: 'Islandés',
  },
  {
    title: 'Ficciones',
    author: 'Jorge Luis Borges',
    year: 1944,
    country: 'Argentina',
    language: 'Español',
  },
  {
    title: 'Todo se desmorona',
    author: 'Chinua Achebe',
    year: 1958,
    country: 'Nigeria',
    language: 'Inglés',
  },
  {
    title: 'Orgullo y prejuicio',
    author: 'Jane Austen',
    year: 1813,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Papá Goriot',
    author: 'Honoré de Balzac',
    year: 1835,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    year: 1953,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Cumbres Borrascosas',
    author: 'Emily Brontë',
    year: 1847,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'El extranjero',
    author: 'Albert Camus',
    year: 1942,
    country: 'Argelia',
    language: 'Francés',
  },
  { title: 'Poemas', author: 'Paul Celan', year: 1952, country: 'Rumanía', language: 'Alemán' },
  {
    title: 'Viaje al fin de la noche',
    author: 'Louis-Ferdinand Céline',
    year: 1932,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'Relatos cortos',
    author: 'Antón Chéjov',
    year: 1886,
    country: 'Rusia',
    language: 'Ruso',
  },
  {
    title: 'Nostromo',
    author: 'Joseph Conrad',
    year: 1904,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Grandes Esperanzas',
    author: 'Charles Dickens',
    year: 1861,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Jacques el fatalista',
    author: 'Denis Diderot',
    year: 1796,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'Berlin Alexanderplatz',
    author: 'Alfred Döblin',
    year: 1929,
    country: 'Alemania',
    language: 'Alemán',
  },
  {
    title: 'Crimen y castigo',
    author: 'Fiódor Dostoievski',
    year: 1866,
    country: 'Rusia',
    language: 'Ruso',
  },
  {
    title: 'El idiota',
    author: 'Fiódor Dostoievski',
    year: 1869,
    country: 'Rusia',
    language: 'Ruso',
  },
  {
    title: 'Los endemoniados',
    author: 'Fiódor Dostoievski',
    year: 1872,
    country: 'Rusia',
    language: 'Ruso',
  },
  {
    title: 'Los hermanos Karamazov',
    author: 'Fiódor Dostoievski',
    year: 1880,
    country: 'Rusia',
    language: 'Ruso',
  },
  {
    title: 'Middlemarch',
    author: 'George Eliot',
    year: 1871,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'El hombre invisible',
    author: 'Ralph Ellison',
    year: 1952,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: '¡Absalom, Absalom!',
    author: 'William Faulkner',
    year: 1936,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'El ruido y la furia',
    author: 'William Faulkner',
    year: 1929,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Madame Bovary',
    author: 'Gustave Flaubert',
    year: 1857,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'La educación sentimental',
    author: 'Gustave Flaubert',
    year: 1869,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'Romancero gitano',
    author: 'Federico García Lorca',
    year: 1928,
    country: 'España',
    language: 'Español',
  },
  {
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    year: 1967,
    country: 'Colombia',
    language: 'Español',
  },
  {
    title: 'El amor en los tiempos del cólera',
    author: 'Gabriel García Márquez',
    year: 1985,
    country: 'Colombia',
    language: 'Español',
  },
  {
    title: 'Moby Dick',
    author: 'Herman Melville',
    year: 1851,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Almas muertas',
    author: 'Nikolai Gogol',
    year: 1842,
    country: 'Ucrania',
    language: 'Ruso',
  },
  {
    title: 'El tambor de hojalata',
    author: 'Günter Grass',
    year: 1959,
    country: 'Alemania Occidental',
    language: 'Alemán',
  },
  {
    title: 'Gran Sertón: Veredas',
    author: 'João Guimarães Rosa',
    year: 1956,
    country: 'Brasil',
    language: 'Portugués',
  },
  { title: 'Hambre', author: 'Knut Hamsun', year: 1890, country: 'Noruega', language: 'Noruego' },
  {
    title: 'El viejo y el mar',
    author: 'Ernest Hemingway',
    year: 1952,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Casa de muñecas',
    author: 'Henrik Ibsen',
    year: 1879,
    country: 'Noruega',
    language: 'Noruego',
  },
  { title: 'Ulises', author: 'James Joyce', year: 1922, country: 'Irlanda', language: 'Inglés' },
  {
    title: 'Relatos cortos',
    author: 'Franz Kafka',
    year: 1924,
    country: 'Checoslovaquia',
    language: 'Alemán',
  },
  {
    title: 'El proceso',
    author: 'Franz Kafka',
    year: 1925,
    country: 'Checoslovaquia',
    language: 'Alemán',
  },
  {
    title: 'El castillo',
    author: 'Franz Kafka',
    year: 1926,
    country: 'Checoslovaquia',
    language: 'Alemán',
  },
  {
    title: 'El sonido de la montaña',
    author: 'Yasunari Kawabata',
    year: 1954,
    country: 'Japón',
    language: 'Japonés',
  },
  {
    title: 'Zorba, el griego',
    author: 'Nikos Kazantzakis',
    year: 1946,
    country: 'Grecia',
    language: 'Griego moderno',
  },
  {
    title: 'Hijos y amantes',
    author: 'D. H. Lawrence',
    year: 1913,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Poemas',
    author: 'Giacomo Leopardi',
    year: 1818,
    country: 'Italia',
    language: 'Italiano',
  },
  {
    title: 'El cuaderno dorado',
    author: 'Doris Lessing',
    year: 1962,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Pippi Calzaslargas',
    author: 'Astrid Lindgren',
    year: 1945,
    country: 'Suecia',
    language: 'Sueco',
  },
  { title: 'Diario de un loco', author: 'Lu Xun', year: 1918, country: 'China', language: 'Chino' },
  {
    title: 'Hijos de nuestro barrio',
    author: 'Naguib Mahfuz',
    year: 1959,
    country: 'Egipto',
    language: 'Árabe',
  },
  {
    title: 'Los Buddenbrook',
    author: 'Thomas Mann',
    year: 1901,
    country: 'Alemania',
    language: 'Alemán',
  },
  {
    title: 'La montaña mágica',
    author: 'Thomas Mann',
    year: 1924,
    country: 'Alemania',
    language: 'Alemán',
  },
  {
    title: 'Moby-Dick',
    author: 'Herman Melville',
    year: 1851,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Ensayos',
    author: 'Michel de Montaigne',
    year: 1595,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'La historia',
    author: 'Elsa Morante',
    year: 1974,
    country: 'Italia',
    language: 'Italiano',
  },
  {
    title: 'Beloved',
    author: 'Toni Morrison',
    year: 1987,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Lolita',
    author: 'Vladimir Nabokov',
    year: 1955,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: '1984',
    author: 'George Orwell',
    year: 1949,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Libro del desasosiego',
    author: 'Fernando Pessoa',
    year: 1928,
    country: 'Portugal',
    language: 'Portugués',
  },
  {
    title: 'Pedro Páramo',
    author: 'Juan Rulfo',
    year: 1955,
    country: 'México',
    language: 'Español',
  },
  { title: 'Masnavi', author: 'Rumi', year: 1258, country: 'Persia', language: 'Persa' },
  {
    title: 'Hijos de la medianoche',
    author: 'Salman Rushdie',
    year: 1981,
    country: 'India',
    language: 'Inglés',
  },
  { title: 'Bostan', author: 'Saadi', year: 1257, country: 'Persia', language: 'Persa' },
  {
    title: 'Tiempo de migrar al norte',
    author: 'Tayeb Salih',
    year: 1966,
    country: 'Sudán',
    language: 'Árabe',
  },
  {
    title: 'Ensayo sobre la ceguera',
    author: 'José Saramago',
    year: 1995,
    country: 'Portugal',
    language: 'Portugués',
  },
  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    year: 1603,
    country: 'Inglaterra',
    language: 'Inglés',
  },
  {
    title: 'El rey Lear',
    author: 'William Shakespeare',
    year: 1608,
    country: 'Inglaterra',
    language: 'Inglés',
  },
  {
    title: 'Otelo',
    author: 'William Shakespeare',
    year: 1609,
    country: 'Inglaterra',
    language: 'Inglés',
  },
  {
    title: 'Rojo y negro',
    author: 'Stendhal',
    year: 1830,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'Rayuela',
    author: 'Julio Cortázar',
    year: 1963,
    country: 'Argentina',
    language: 'Español',
  },
  {
    title: 'La conciencia de Zeno',
    author: 'Italo Svevo',
    year: 1923,
    country: 'Italia',
    language: 'Italiano',
  },
  {
    title: 'Los viajes de Gulliver',
    author: 'Jonathan Swift',
    year: 1726,
    country: 'Irlanda',
    language: 'Inglés',
  },
  { title: 'Ana Karenina', author: 'Lev Tolstói', year: 1877, country: 'Rusia', language: 'Ruso' },
  {
    title: 'La muerte de Iván Ilich',
    author: 'Lev Tolstói',
    year: 1886,
    country: 'Rusia',
    language: 'Ruso',
  },
  {
    title: 'Las aventuras de Huckleberry Finn',
    author: 'Mark Twain',
    year: 1884,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Hojas de hierba',
    author: 'Walt Whitman',
    year: 1855,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'La señora Dalloway',
    author: 'Virginia Woolf',
    year: 1925,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Al faro',
    author: 'Virginia Woolf',
    year: 1927,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'Memorias de Adriano',
    author: 'Marguerite Yourcenar',
    year: 1951,
    country: 'Francia',
    language: 'Francés',
  },
  { title: '2666', author: 'Roberto Bolaño', year: 2004, country: 'España', language: 'Español' },
  {
    title: 'A sangre fría',
    author: 'Truman Capote',
    year: 1966,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'Canto general',
    author: 'Pablo Neruda',
    year: 1950,
    country: 'México',
    language: 'Español',
  },
  {
    title: 'Cinco horas con Mario',
    author: 'Miguel Delibes',
    year: 1966,
    country: 'España',
    language: 'Español',
  },
  {
    title: 'Confesiones de una máscara',
    author: 'Yukio Mishima',
    year: 1949,
    country: 'Japón',
    language: 'Japonés',
  },
  {
    title: 'Drácula',
    author: 'Bram Stroker',
    year: 1897,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'El Aleph',
    author: 'Jorge Luis Borges',
    year: 1942,
    country: 'Argentina',
    language: 'Español',
  },
  {
    title: 'El Buscón',
    author: 'Francisco de Quevedo',
    year: 1626,
    country: 'España',
    language: 'Español',
  },
  {
    title: 'El Principito',
    author: 'Antoine de Saint-Exupery',
    year: 1943,
    country: 'Francia',
    language: 'Francés',
  },
  { title: 'El Tartufo', author: 'Molière', year: 1664, country: 'Francia', language: 'Francés' },
  {
    title: 'El conde de Montecristo',
    author: 'Alejandro Dumas',
    year: 1844,
    country: 'Francia',
    language: 'Francés',
  },
  {
    title: 'El gran Gatsby',
    author: 'Scott Fitzgerald',
    year: 1925,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'El guardián entre el centeno',
    author: 'J.D. Salinger',
    year: 1951,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
  {
    title: 'El laberinto de la soledad',
    author: 'Octavio Paz',
    year: 1950,
    country: 'México',
    language: 'Español',
  },
  {
    title: 'El retrato de Dorian Gray',
    author: 'Óscar Wilde',
    year: 1890,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'El señor de las moscas',
    author: 'William Golding',
    year: 1954,
    country: 'Reino Unido',
    language: 'Inglés',
  },
  {
    title: 'En el camino',
    author: 'Jack Kerouac',
    year: 1957,
    country: 'Estados Unidos',
    language: 'Inglés',
  },
];

export default books;
